[package]
name = "spectrum-analyzer"
description = """
A library to filter out the frequencies of a digital signal (e.g. audio) using FFT. The main goal of this crate
is to be educational to the world and myself. This is not a bullet-proof or ideal solution! Feel free to contribute,
improve, and point out possible errors/bugs/wrong assumptions.
"""
version = "0.1.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["ffi", "spectrum", "frequencies", "audio", "dsp"]
categories = ["multimedia", "no-std"]
readme = "README.md"
license = "MIT"

homepage = "https://github.com/phip1611/spectrum-analyzer"
repository = "https://github.com/phip1611/spectrum-analyzer"
documentation = "https://docs.rs/spectrum-analyzer"

[dependencies]
rustfft = "5.0.1"

[dev-dependencies]
minimp3 = "0.5.1"

# otherwise FFT and other code is too slow
[profile.dev]
opt-level = 1
