[package]
name = "spectrum-analyzer"
description = """
A simple and fast `no_std` library to get the frequency spectrum of a digital signal (e.g. audio) using FFT.
It follows the KISS principle and consists of simple building blocks/optional features.
"""
version = "0.2.2"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["fft", "spectrum", "frequencies", "audio", "dsp"]
categories = ["multimedia", "no-std"]
readme = "README.md"
license = "MIT"

homepage = "https://github.com/phip1611/spectrum-analyzer"
repository = "https://github.com/phip1611/spectrum-analyzer"
documentation = "https://docs.rs/spectrum-analyzer"

[dependencies]
rustfft = "5.0.1"
float-cmp = "0.8.0" # approx. compare floats

[dev-dependencies]
minimp3 = "0.5.1"
audio-visualizer = "0.2.1"

# otherwise FFT and other code is too slow
[profile.dev]
opt-level = 1
